services:
    - type: web
    name: connect-tics-api
    env: python
    rootDir: backend/src   # <- TROCA AQUI: era só 'backend'
    buildCommand: "pip install -r ../requirements.txt"  # <- TROCA AQUI: sobe 1 pasta pra achar o requirements
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"  # <- TROCA AQUI: era 'src.main:app'
    autoDeploy: true
